<a href="https://colab.research.google.com/github/ArthurCBx/Applied_Text_Mining/blob/main/module%203/Classification_of_Text.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Text Classification
## Examples of Text Classification
- Topic identification: Is this news article about Politics, Sports, or Technology?
- Spam Detection: Is this email a spam or not?
- Sentiment analysis: Is this movie review positive or negative?
- Spelling correction: weather or whether ? Color or colour?

## Supervised Learning
- Machines learns from past instances;
### Supervised Classification
- Training phase:
  - Labeled input;
  - Classification algorithm;
  - Classification model is trained;
- Inference phase:
  - Unlabeled input;
  - Classfication model outputs predicted answer.

- Learn a classification model on properties("features") and their importance("weights") from labeled instances:
  - X: Set of attributes or features ${x_1,x_2,...,x_n}$;
  - y: A class label from the label set Y = ${y_1,y_2,...,y_n}$;

- Apply the model on new instances to predict the label.

## Classification paradigms
- When there are only 2 possible classes => Binary Classification;
- When there are more than 2 possible classes => Multi-class Classification;
- When data instances can have 2 or more labels => Multi-label Classification.

## Questions to ask in Supervised Learning
- Training phase:
  - What are the features? How do you represent them?
  - What is the classification model/algorithm;
  - What are the model parameter?

- Inference phase:
  - What is the expected performance? What is a good measure?

# Identifying Features from Text

## Why is textual data unique?
- Textual data present an unique set of challenges;
- All the information you need is in the text;
- But features can be pulled out from text at different granularities;

## Types of textual features (I)
- Words:
  - By far the most common class of features;
  - Handling commonly-occurring words: Stop words ('the', 'a',...);
  - Normalization: Make lower case vs leave as-is;
  - Stemming/Lemmatization;

## Types of textual features (II)
- Characteristics of words: Capitalize;
- Parts of speech of words in sequence;
- Grammatical structure, sentence parsing;
- Grouping words of similar meaning, semantics:
  - {buy, purchase};
  - {Mr., Ms., Dr., Prof.};
  - Numbers/Digits;
  - Dates
## Types of textual features (III)
- Depending on classification tasks, features may come from inside words and word sequence:
  - Bigrams, trigrams, n-grams;
  - Character sub-sequences in words: "ing", "ion".

# Naive Bayes Classifiers
## Case study: Classifying text search queries
- Suppose you are interested in classifying search queries in 3 classes: Entertainment, Computer Science, Zoology;
- Most common class of the three is Enternainment;
- Suppose the query is "Python":
  - Python, the snake(Zoology);
  - Python, the programming language (Computer Science);
  - Python, as in Monty Python (Entertainment).

  - Most common class, given "Python", is Zoology.

  - Suppose the query is "Python download". Then the most probable class is Computer Science.

### Probabilistic model
- Update the likelihood of the class given new information;
- Prior Probability: Pr(y=Entertainment), Pr(y=CS), Pr(y=Zoology);
- Posterior probability: Pr(y=Entertainment|x="Python"),...

## Bayes' Rule
$Posterior\, probability = \frac{Prior\, probability\, *\, Likelihood}{Evidence}$

$Pr(y|x) = \frac{PR(y)\, *\, Pr(X|y)}{Pr(X)}$

## Naive Bayes Classification
- $Pr(CS|"Python")= \frac{PR(y=CS)\, *\, Pr("Python"|y=CS)}{Pr("Python")}$

- $Pr(Zoology|"Python")= \frac{PR(y=Zoology)\, *\, Pr("Python"|y=Zoology)}{Pr("Python")}$

- $Pr(CS|"Python")>Pr(Zoology|"Python") => y=CS$

- $y^* = argmax_y\, Pr(y|X) = argmax_y\, Pr(y)\, *\, Pr (X|y)$

### Naive assumption
- Given the class label, features are assumed to be independent of each other.
- $y^* = argmax_y\, Pr(y|X) = argmax_y\, Pr(y)\, *\, \prod_{i=1}^{n} Pr (X_i|y)$
- For the query "Python download" we have:
  $y^* = argmax_y\, Pr(y)\, *\, Pr("Python"|y)\, *\, Pr("download"|y)$

## Naive Bayes: What are the parameters
- Prior probabilities: Pr(y) for all y in Y;
- Likelihood: Pr($x_i$|y) for all features $x_i$ and labels y in Y
- If there are 3 clases (Y=3) and 100 features in X, how many parameters does Naive Bayes models have ?
R: Y + 2 * X * Y = 603

## Naive Bayes: Learning parameters
- Prior probabilities: Pr(y) for all y in Y:
  - Acquired from the training data;
  - Count the number of instances in each class;
  - If there are N instances in all, and n out of those are labeled as class y => Pr(y) = n/N

- Likelihood: Pr($x_i$|y) for all features $x_i$ and labels y in Y:
  - Count how many times features $x_i$ appears in instances labeled as class y;
  - If there are p instances of class y, and $x_i$ appears in k of those, Pr($x_i$|y)= k/p

## Naive Bayes: Smoothing
- What happens if Pr($x_i$|y) = 0 ?
  - Feature $x_i$ never occurs in documents labeled y;
  - But then, the posterior probability Pr(y|$x_i$) will be 0
- Instead, smooth the parameters;
- Laplace smoothing or Addictive smoothing: Add a dummy count:
  - Pr($x_i$|y)= (k+1)/(p+n)

# Naive Bayes Variations

## Two Classic Naive Bayes Variants for Text
1. Multinomial Naive Bayes
  - Data follows a multinomial distribution;
  - Each feature value is a count (word occurrence counts, TF-IDF weighting,...)
2. Bernoulli Naive Bayes
  - Data follows a multivariate Bernoulli distribuition;
  - Each feature is binary.

# Support Vector Machines

## Decision Boundaries
- Classification function is represented by decision surfaces;
- Choosing a Decision Boundary:
  - Training data;
  - Caution with overfitting: Decision boundary learned over training data doesn't generalize to test data.
### Linear Boundaries:
- Characteristics:
  - Easy to find;
  - Easy to evaluate;
  - More generalizable: "Occam's razor"
- Finding a Linear Boundary:
  - Find the angular parameter w;
  - Many methods: Perceptron, Linear Least Squares, Linear Discriminative Analysis ...
  - Problem: If linearly separable, then infinite number of linear boundaries

## Support Vector Machines (SVM)
- Support Vector Machines are maximum-margin classifiers;
- They're linear classifiers that find a hyperplane to separate two classes of data: positive and negative;
- Given training data, SVMs finds a linear function w (weight vector):
  - $f(x_i) =\, <w.x_i> + b$
  - if $f(x_i)\geq 0, y_i = +1;else\,y_i = -1$

## SVM: Multi-class classification
- SVMs work only for binary classification problems;
- 2 different situations:
  - One vs Rest: For each class you train a different SVM that detect if an input is from a specific class or not.
  - One vs One: Train one SVM for each pair of classes. Total number of SVMs to be trained is a combinatory of n, 2 by 2.

## SVM Parameters (I): Parameter C
- Regularization: How much importance should you give individual data points as compared to better generalized model;
- Larger values of C = less regularization:
  - Fit training data as well as possible, every data point important;
- Small values of c = more regularization:
  - More tolerant to erros on individual data points.

## SVM Parameters (II): Other params
- Linear kernels usually work best for text data:
  - Other kernels include rbf, polynomial;
- multi_class: ovr(one-vs-rest);
- class_weight: Different classes can get different weights

# Learning Text Classifiers in Python
## Toolkits for Supervised Text Classification
- Scikit-learn;
- NLTK - interfaces with sklearn and other ML toolkits.

## Scikit-learn
- Open-source Machine Learning library;
- Has a more programmatic interface

## Using SKlearn's NaiveBayesClassifier
```python
from sklearn import naive_bayes

clfrNB = naive_bayes.MultinomialNB()
clfrNB.fit(train_data, train_labels)
predicted_labels = clfrNB.predict(test_data)
metrics.f1_score(test_labels, predicted_labels, average='micro')
```

## Using Sklearn's SVM classifier
```python
from sklearn import svm

clfrSVM = svm.SVC(kernel='linear',C=0.1)
clfrSVM.fit(train_data, train_labels)
predicted_labels = clfrSVM.predict(test_data)
metrics.f1_score(test_labels, predicted_labels, average='micro')
```

## Model Selection
- Recall the discussion on multiple phases in a supervised learning task:
  - Training phase;
  - Validation Data set;
  - Test Data set.

### Model Selection in scikit-learn
```python
from sklearn import model_selection

# Normal train and test split
X_train, X_test, y_train, y_test = model_selection.train_test_split(train_data, train_labels, test_size=0.333)

# Cross validation method (specifying to train 5 different models)
predicted_labels = model_selection.cross_val_predict(clfrSVM, train_data, train_labels, cv=5)
```

## Supervised Text Classification in NLTK
- NLTK has some classification algorithms:
  - NaiveBayesClassifier;
  - DecisionTreeClassifier;
  - ConditionalExponentialClassifier;
  - MaxentClassifier;
  - WekaClassifier;
  - SklearnClassifier.

### Using NLTK's NaiveBayesClassifier
```python
from nltk.classify import NaiveBayesClassifier

classifier = NaiveBayesClassifier.train(train_set)

classifier.classify(unlabeled_instance)
classifier.classify_many(unlabeled_instances)

nltk.classify.util.accuracy(classifier, test_set)

# To show the labels the classifier was trained on
classifier.labels()

# Get information about the model's features
classifier.show_most_informative_features()
```

### Using NLTK's SklearnClassifier
```python
from nltk.classify impor SklearnClassifier
from sklearn.naive_bayes import MultinomialNB
from skearn.svm import SVC

clfrNB = SklearnClassifier(MultinomialNB()).train(train_set)

clfrVSM = SklearnClassifier(SVC(), kernel='linear').train(train_set)
```

# Case Study - Sentiment Analysis

In [ ]:
!git clone https://github.com/ArthurCBx/Applied_Text_Mining.git

fatal: destination path 'Applied_Text_Mining' already exists and is not an empty directory.

## Data Prep

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('/content/Applied_Text_Mining/module 3/Amazon_Unlocked_Mobile.zip')

df.head()

,Product Name,Brand Name,Price,Rating,Reviews,Review Votes
0,"""CLEAR CLEAN ESN"" Sprint EPIC 4G Galaxy SPH-D7...",Samsung,199.99,5,I feel so LUCKY to have found this used (phone...,1.0
1,"""CLEAR CLEAN ESN"" Sprint EPIC 4G Galaxy SPH-D7...",Samsung,199.99,4,"nice phone, nice up grade from my pantach revu...",0.0
2,"""CLEAR CLEAN ESN"" Sprint EPIC 4G Galaxy SPH-D7...",Samsung,199.99,5,Very pleased,0.0
3,"""CLEAR CLEAN ESN"" Sprint EPIC 4G Galaxy SPH-D7...",Samsung,199.99,4,It works good but it goes slow sometimes but i...,0.0
4,"""CLEAR CLEAN ESN"" Sprint EPIC 4G Galaxy SPH-D7...",Samsung,199.99,4,Great phone to replace my lost phone. The only...,0.0

In [ ]:
df = df.dropna()

# Removing neutral reviews
df = df[df['Rating'] != 3]

# Creating a column with positive reviews binary encoded
df['Positively Rated'] = np.where(df['Rating'] > 3, 1, 0)
df.head(10)

,Product Name,Brand Name,Price,Rating,Reviews,Review Votes,Positively Rated
0,"""CLEAR CLEAN ESN"" Sprint EPIC 4G Galaxy SPH-D7...",Samsung,199.99,5,I feel so LUCKY to have found this used (phone...,1.0,1
1,"""CLEAR CLEAN ESN"" Sprint EPIC 4G Galaxy SPH-D7...",Samsung,199.99,4,"nice phone, nice up grade from my pantach revu...",0.0,1
2,"""CLEAR CLEAN ESN"" Sprint EPIC 4G Galaxy SPH-D7...",Samsung,199.99,5,Very pleased,0.0,1
3,"""CLEAR CLEAN ESN"" Sprint EPIC 4G Galaxy SPH-D7...",Samsung,199.99,4,It works good but it goes slow sometimes but i...,0.0,1
4,"""CLEAR CLEAN ESN"" Sprint EPIC 4G Galaxy SPH-D7...",Samsung,199.99,4,Great phone to replace my lost phone. The only...,0.0,1
5,"""CLEAR CLEAN ESN"" Sprint EPIC 4G Galaxy SPH-D7...",Samsung,199.99,1,I already had a phone with problems... I know ...,1.0,0
6,"""CLEAR CLEAN ESN"" Sprint EPIC 4G Galaxy SPH-D7...",Samsung,199.99,2,The charging port was loose. I got that solder...,0.0,0
7,"""CLEAR CLEAN ESN"" Sprint EPIC 4G Galaxy SPH-D7...",Samsung,199.99,2,"Phone looks good but wouldn't stay charged, ha...",0.0,0
8,"""CLEAR CLEAN ESN"" Sprint EPIC 4G Galaxy SPH-D7...",Samsung,199.99,5,I originally was using the Samsung S2 Galaxy f...,0.0,1
11,"""CLEAR CLEAN ESN"" Sprint EPIC 4G Galaxy SPH-D7...",Samsung,199.99,5,This is a great product it came after two days...,0.0,1

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df['Reviews'],
                                                    df['Positively Rated'],
                                                    random_state=0)

In [ ]:
print('X_train first entry:\n\n',X_train[0])
print('\n\nX_train shape: ',X_train.shape)

X_train first entry:

 I feel so LUCKY to have found this used (phone to us & not used hard at all), phone on line from someone who upgraded and sold this one. My Son liked his old one that finally fell apart after 2.5+ years and didn't want an upgrade!! Thank you Seller, we really appreciate it & your honesty re: said used phone.I recommend this seller very highly & would but from them again!!


X_train shape:  (231202,)

## CountVectorizer

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

vect = CountVectorizer().fit(X_train)

In [ ]:
vect.get_feature_names_out()[::2000]

array(['00', '4h', 'adpaters', 'assembly', 'blasts', 'cashiers',
       'condidtion', 'debit', 'domestic', 'estimates', 'flawlessy',
       'gothrough', 'hui', 'irritating', 'lighting5', 'microcomputer',
       'nigeria', 'p7_l00', 'poorer', 'quirkyness', 'responsibility',
       'sens', 'sorrow', 'synch', 'trace', 'usvi', 'within3'],
      dtype=object)

In [ ]:
len(vect.get_feature_names_out())

53271

In [ ]:
X_train_vectorized = vect.transform(X_train)

X_train_vectorized

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 6113585 stored elements and shape (231202, 53271)>

In [ ]:
from sklearn.linear_model import LogisticRegression

# LogisticRegression is a great option to work with high-dimensional sparse data
# such as a word tokenized vector
model = LogisticRegression(max_iter=1000)
model.fit(X_train_vectorized, y_train)

LogisticRegression(max_iter=1000)

In [ ]:
from sklearn.metrics import roc_auc_score

predictions = model.predict(vect.transform(X_test))
print('AUC: ', roc_auc_score(y_test, predictions))

AUC:  0.9302075046618711

In [ ]:
feature_names = np.array(vect.get_feature_names_out())
sorted_coef_index = model.coef_[0].argsort()

print(f'Smallest Coefs:\n{feature_names[sorted_coef_index[:10]]}\n')
print(f'Largest Coefs:\n{feature_names[sorted_coef_index[:-11:-1]]}')

Smallest Coefs:
['mony' 'worst' 'horribly' 'false' 'blacklist' 'dissatisfied' 'rubbish'
 'worthless' 'unsatisfied' 'junk']

Largest Coefs:
['excelente' 'excelent' '4eeeks' 'efficient' 'excellent' 'pleasantly'
 'loving' 'loves' 'lovely' 'satisfy']

## Tfidf
- Term frequency inverse document frequency allows us to weight terms based on how important they're to a document

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

# This min_df parameter will remove from the vector tokens that only appear
# in less than 5 reviews
vect = TfidfVectorizer(min_df=5).fit(X_train)
len(vect.get_feature_names_out())

18024

In [ ]:
from sklearn.linear_model import LogisticRegression
X_train_vectorized = vect.transform(X_train)

model = LogisticRegression(max_iter=1000)
model.fit(X_train_vectorized, y_train)

predictions = model.predict(vect.transform(X_test))

print('AUC with reduced tokens:', roc_auc_score(y_test, predictions))

AUC with reduced tokens: 0.9272635538611583

About the same score with 35k less features

In [ ]:
feature_names = np.array(vect.get_feature_names_out())

sorted_tfidf_index = X_train_vectorized.max(0).toarray()[0].argsort()
print(f'Smallest tfidf:\n{feature_names[sorted_tfidf_index[:10]]}\n')
print(f'Largest tfidf:\n{feature_names[sorted_tfidf_index[:-11:-1]]}')

Smallest tfidf:
['aggregration' 'pthalo' 'warmness' 'storageso' 'commenter' '1300' '770'
 'resins' 'srgb' 'glues']

Largest tfidf:
['13' 'sistem' '0k' '10' '100' 'correct' 'cumple' 'cute' 'dandy'
 'contenta']

In [ ]:
feature_names = np.array(vect.get_feature_names_out())
sorted_coef_index = model.coef_[0].argsort()

print(f'Smallest coefs:\n{feature_names[sorted_coef_index[:10]]}\n')
print(f'Largest coefs:\n{feature_names[sorted_coef_index[:-11:-1]]}')

Smallest coefs:
['not' 'worst' 'useless' 'terrible' 'waste' 'disappointed' 'return' 'poor'
 'returning' 'slow']

Largest coefs:
['great' 'love' 'excellent' 'amazing' 'perfect' 'loves' 'perfectly' 'easy'
 'awesome' 'best']

In [ ]:
# Because the model does not count relation between words the 2 following sentences
# are interpreted in the same way
print(model.predict(vect.transform(['not an issue, phone is working',
                                    'an issue, phone is not working'])))

[0 0]

## n-grams
- Deal with the relation of a given number of words;
- The number of tokens will grow exponentially

In [ ]:
vect = CountVectorizer(min_df=5,ngram_range=(1,2)).fit(X_train)
X_train_vectorized = vect.transform(X_train)

len(vect.get_feature_names_out())

200192

In [ ]:
model = LogisticRegression(max_iter=1000)
model.fit(X_train_vectorized, y_train)

predictions = model.predict(vect.transform(X_test))

print('AUC: ', roc_auc_score(y_test,predictions))

AUC:  0.9673064845875721

In [ ]:
feature_names = np.array(vect.get_feature_names_out())
sorted_coef_index = model.coef_[0].argsort()

print(f'Smallest coefs:\n{feature_names[sorted_coef_index[:10]]}\n')
print(f'Largest coefs:\n{feature_names[sorted_coef_index[:-11:-1]]}')

Smallest coefs:
['no good' 'junk' 'worst' 'not good' 'horrible' 'terrible' 'not very'
 'looks ok' 'not happy' 'garbage']

Largest coefs:
['not bad' 'excelent' 'excelente' 'excellent' 'no problems' 'perfect'
 'no issues' 'awesome' 'exelente' 'amazing']

In [ ]:
# Now the same 2 sentences are classified differently
print(model.predict(vect.transform(['not an issue, phone is working',
                                    'an issue, phone is not working'])))

[1 0]

# Assignment 3

In this assignment you will explore text message data and create models to predict if a message is spam or not.

In [ ]:
import pandas as pd
import numpy as np

spam_data = pd.read_csv('Applied_Text_Mining/module 3/spam.csv')

spam_data['target'] = np.where(spam_data['target']=='spam',1,0)
spam_data.head(10)

                                                text  target
0  Go until jurong point, crazy.. Available only ...       0
1                      Ok lar... Joking wif u oni...       0
2  Free entry in 2 a wkly comp to win FA Cup fina...       1
3  U dun say so early hor... U c already then say...       0
4  Nah I don't think he goes to usf, he lives aro...       0
5  FreeMsg Hey there darling it's been 3 week's n...       1
6  Even my brother is not like to speak with me. ...       0
7  As per your request 'Melle Melle (Oru Minnamin...       0
8  WINNER!! As a valued network customer you have...       1
9  Had your mobile 11 months or more? U R entitle...       1

In [ ]:
from sklearn.model_selection import train_test_split


X_train, X_test, y_train, y_test = train_test_split(spam_data['text'],
                                                    spam_data['target'],
                                                    random_state=0)

### Question 1
What percentage of the documents in `spam_data` are spam?

*This function should return a float, the percent value (i.e. $ratio * 100$).*

In [ ]:
def answer_one():
    total_spam = spam_data['target'].sum()
    total_spam_ratio = total_spam/spam_data.shape[0]
    return total_spam_ratio*100

answer_one()

np.float64(13.406317300789663)

### Question 2

Fit the training data `X_train` using a Count Vectorizer with default parameters.

What is the longest token in the vocabulary?

*This function should return a string.*

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

def answer_two():
    tokenized_text = CountVectorizer().fit(X_train)
    tokens = np.array(tokenized_text.get_feature_names_out())
    return sorted(tokens,key=lambda x: len(x),reverse=True)[0]

answer_two()

'com1win150ppmx3age16subscription'

### Question 3

Fit and transform the training data `X_train` using a Count Vectorizer with default parameters.

Next, fit a fit a multinomial Naive Bayes classifier model with smoothing `alpha=0.1`. Find the area under the curve (AUC) score using the transformed test data.

*This function should return the AUC score as a float.*

In [ ]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import roc_auc_score

def answer_three():

  vect = CountVectorizer().fit(X_train)
  X_train_transformed = vect.transform(X_train)

  model = MultinomialNB(alpha=0.1).fit(X_train_transformed, y_train)
  predictions = model.predict_proba(vect.transform(X_test))[:, 1]

  return roc_auc_score(y_test,predictions)

answer_three()

np.float64(0.991545422134696)

### Question 4

Fit and transform the training data `X_train` using a Tfidf Vectorizer with default parameters. The transformed data will be a compressed sparse row matrix where the number of rows is the number of documents in `X_train`, the number of columns is the number of features found by the vectorizer in each document, and each value in the sparse matrix is the tf-idf value. First find the **max** tf-idf value for every feature.

What 20 features have the smallest tf-idf and what 20 have the largest tf-idf among the **max** tf-idf values?

Put these features in two series where each series is sorted by tf-idf value. The index of the series should be the feature name, and the data should be the tf-idf.

The series of 20 features with smallest tf-idfs should be sorted smallest tfidf first, the list of 20 features with largest tf-idfs should be sorted largest first. Any entries with identical tf-ids should appear in lexigraphically increasing order by their feature name in boh series. For example, if the features "a", "b", "c" had the tf-idfs 1.0, 0.5, 1.0 in the series with the largest tf-idfs, then they should occur in the returned result in the order "a", "c", "b" with values 1.0, 1.0, 0.5.

*This function should return a tuple of two series
`(smallest tf-idfs series, largest tf-idfs series)`.*

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

def answer_four():

    tfidf_vect = TfidfVectorizer().fit(X_train)
    X_train_transformed = tfidf_vect.transform(X_train)

    max_tfidfs = X_train_transformed.max(axis=0).toarray()[0]
    feature_names = np.array(tfidf_vect.get_feature_names_out())

    sorted_tfidf_indices = max_tfidfs.argsort()

    # Smallest 20 tf-idf values
    smallest_tfidfs_indices = sorted_tfidf_indices[:20]
    smallest_tfidfs_values = max_tfidfs[smallest_tfidfs_indices]
    smallest_tfidfs_features = feature_names[smallest_tfidfs_indices]

    smallest_tfidfs_series = pd.Series(smallest_tfidfs_values, index=smallest_tfidfs_features)

    # Largest 20 tf-idf values
    largest_tfidfs_indices = sorted_tfidf_indices[-20:][::-1] # Reverse to get largest first
    largest_tfidfs_values = max_tfidfs[largest_tfidfs_indices]
    largest_tfidfs_features = feature_names[largest_tfidfs_indices]

    largest_tfidfs_series = pd.Series(largest_tfidfs_values, index=largest_tfidfs_features)

    # Sorting them lexicographically
    smallest_tfidfs_series = smallest_tfidfs_series.sort_index().sort_values(kind='mergesort')
    largest_tfidfs_series = largest_tfidfs_series.sort_index().sort_values(kind='mergesort',ascending=False)
    return (smallest_tfidfs_series,largest_tfidfs_series)

answer_four()

(aaniye          0.074475
 athletic        0.074475
 chef            0.074475
 companion       0.074475
 courageous      0.074475
 dependable      0.074475
 determined      0.074475
 exterminator    0.074475
 healer          0.074475
 listener        0.074475
 organizer       0.074475
 pest            0.074475
 psychiatrist    0.074475
 psychologist    0.074475
 pudunga         0.074475
 stylist         0.074475
 sympathetic     0.074475
 venaam          0.074475
 teachers        0.091250
 ugadi           0.091250
 dtype: float64,
 146tf150p    1.000000
 645          1.000000
 anything     1.000000
 anytime      1.000000
 beerage      1.000000
 done         1.000000
 er           1.000000
 havent       1.000000
 home         1.000000
 lei          1.000000
 nite         1.000000
 ok           1.000000
 okie         1.000000
 thank        1.000000
 thanx        1.000000
 too          1.000000
 where        1.000000
 yup          1.000000
 tick         0.980166
 blank        0.932702
 dtype: float64)

### Question 5

Fit and transform the training data `X_train` using a Tfidf Vectorizer ignoring terms that have a document frequency strictly lower than **3**.

Then fit a multinomial Naive Bayes classifier model with smoothing `alpha=0.1` and compute the area under the curve (AUC) score using the transformed test data.

*This function should return the AUC score as a float.*

In [ ]:
def answer_five():
  vect = TfidfVectorizer(min_df=3).fit(X_train)
  X_train_transformed = vect.transform(X_train)

  model = MultinomialNB(alpha=0.1).fit(X_train_transformed, y_train)
  y_pred = model.predict_proba(vect.transform(X_test))[:, 1]

  return roc_auc_score(y_test, y_pred)

answer_five()

np.float64(0.9954968337775665)

### Question 6

What is the average length of documents (number of characters) for not spam and spam documents?

*This function should return a tuple (average length not spam, average length spam).*

In [ ]:
def answer_six():

  not_spam_df = spam_data[spam_data['target']==0].drop(columns='target')
  not_spam_df['len'] = not_spam_df['text'].apply(lambda x: len(x))

  spam_data_df = spam_data[spam_data['target']==1].drop(columns='target')
  spam_data_df['len'] = spam_data_df['text'].apply(lambda x: len(x))

  return (not_spam_df['len'].mean(), spam_data_df['len'].mean())

answer_six()

np.float64(138.8661311914324)

### Question 7

Fit and transform the training data X_train using a Tfidf Vectorizer ignoring terms that have a document frequency strictly lower than **5**.

Using this document-term matrix and an additional feature, **the length of document (number of characters)**, fit a Support Vector Classification model with regularization `C=10000`. Then compute the area under the curve (AUC) score using the transformed test data.

*Hint: Since probability is set to false, use the model's `decision_function` on the test data when calculating the target scores to use in roc_auc_score*

*This function should return the AUC score as a float.*

In [ ]:
def add_feature(X, feature_to_add):
    """
    Returns sparse feature matrix with added feature.
    feature_to_add can also be a list of features.
    """
    from scipy.sparse import csr_matrix, hstack
    return hstack([X, csr_matrix(feature_to_add).T], 'csr')

In [ ]:
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split

vect = TfidfVectorizer(min_df=5).fit(X_train)
X_train_transformed = vect.transform(X_train)

spam_data['len'] = spam_data['text'].apply(lambda x: len(x))
X_train_len, X_test_len, y_train_len, y_test_len =  train_test_split(spam_data['len'],
                                                    spam_data['target'],
                                                    random_state=0)

X_train_with_len = add_feature(X_train_transformed, X_train_len)
X_test_with_len = add_feature(vect.transform(X_test), X_test_len)

model = SVC(C=10000, kernel='rbf', probability=True)
model.fit(X_train_with_len, y_train)

predictions = model.decision_function(X_test_with_len)

roc_auc_score(y_test, predictions)

np.float64(0.9963202213809143)

### Question 8

What is the average number of digits per document for not spam and spam documents?

*Hint: Use `\d` for digit class*

*This function should return a tuple (average # digits not spam, average # digits spam).*

In [ ]:
def answer_eight():
  digits_count = spam_data['text'].str.findall(r'\d').str.len()
  result = digits_count.groupby(spam_data['target']).mean()

  return (result[0],result[1])
answer_eight()

(np.float64(0.2992746113989637), np.float64(15.759036144578314))

### Question 9

Fit and transform the training data `X_train` using a Tfidf Vectorizer ignoring terms that have a document frequency strictly lower than **5** and using **word n-grams from n=1 to n=3** (unigrams, bigrams, and trigrams).

Using this document-term matrix and the following additional features:
* the length of document (number of characters)
* **number of digits per document**

fit a Logistic Regression model with regularization `C=100` and `max_iter=1000`. Then compute the area under the curve (AUC) score using the transformed test data.

*This function should return the AUC score as a float.*

In [ ]:
from sklearn.linear_model import LogisticRegression
from scipy.sparse import hstack, csr_matrix

digits_count_train = csr_matrix(X_train['text'].str.count(r'\d').to_numpy()).reshape(-1,1)
char_len_train = csr_matrix(X_train['text'].str.len().to_numpy()).reshape(-1,1)

digits_count_test = csr_matrix(X_test['text'].str.count(r'\d').to_numpy()).reshape(-1,1)
char_len_test = csr_matrix(X_test['text'].str.len().to_numpy()).reshape(-1,1)

vect = TfidfVectorizer(min_df=5, ngram_range=(1,3)).fit(X_train['text'])

X_train_transformed = vect.transform(X_train['text'])
X_test_transformed = vect.transform(X_test['text'])

X_train_with_features = hstack([X_train_transformed, digits_count_train, char_len_train])
X_test_with_features = hstack([X_test_transformed, digits_count_test, char_len_test])

model = LogisticRegression(C=100, max_iter=1000).fit(X_train_transformed, y_train)
y_pred = model.predict_proba(X_test_transformed)[:,1]
roc_auc_score(y_test,y_pred)

np.float64(0.9948856594740506)

### Question 10

What is the average number of non-word characters (anything other than a letter, digit or underscore) per document for not spam and spam documents?

*Hint: Use `\w` and `\W` character classes*

*This function should return a tuple (average # non-word characters not spam, average # non-word characters spam).*

In [ ]:
non_char_len = spam_data['text'].str.findall(r'\W').str.len()
non_char_len_mean = non_char_len.groupby(spam_data['target']).mean()

non_char_len_mean[0],non_char_len_mean[1]

(np.float64(17.29181347150259), np.float64(29.041499330655956))

### Question 11

Fit and transform the **first 2000 rows** of training data X_train using a Count Vectorizer ignoring terms that have a document frequency strictly lower than **5** and using **character n-grams from n=2 to n=5.**

To tell Count Vectorizer to use character n-grams pass in `analyzer='char_wb'` which creates character n-grams only from text inside word boundaries. This should make the model more robust to spelling mistakes.

Using this document-term matrix and the following additional features:
* the length of document (number of characters)
* number of digits per document
* **number of non-word characters (anything other than a letter, digit or underscore.)**

fit a Logistic Regression model with regularization C=100 and max_iter=1000. Then compute the area under the curve (AUC) score using the transformed test data.

Also **find the 10 smallest and 10 largest coefficients from the model** and return them along with the AUC score in a tuple.

The list of 10 smallest coefficients should be sorted smallest first, the list of 10 largest coefficients should be sorted largest first.

The three features that were added to the document term matrix should have the following names should they appear in the list of coefficients:
['length_of_doc', 'digit_count', 'non_word_char_count']

*This function should return a tuple `(AUC score as a float, smallest coefs list, largest coefs list)`.*

In [ ]:
def answer_eleven():

  from sklearn.feature_extraction.text import CountVectorizer
  from sklearn.linear_model import LogisticRegression
  from scipy.sparse import hstack

  # Getting the additional features from the text
  digits_count = spam_data['text'].str.findall(r'\d').str.len()
  char_len = spam_data['text'].str.len()
  non_char_len = spam_data['text'].str.findall(r'\W').str.len()

  # Concatenating the addional features in the main dataframe
  expanded_spam_data = pd.concat([spam_data,digits_count,non_char_len],axis=1,names=['length_of_doc','digit_count','non_word_char_count'])
  expanded_spam_data.columns=['text','target','length_of_doc','digit_count','non_word_char_count']

  # Creating the train, test split
  X = expanded_spam_data.drop(columns='target')
  y = expanded_spam_data['target']
  X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=0)

  # Reducing size of train data and vectorizing the text
  X_train_reduced = X_train[:2000]
  y_train_reduced = y_train[:2000]
  vect = CountVectorizer(min_df=5,ngram_range=(2,5),analyzer='char_wb').fit(X_train_reduced['text'])

  # Transforming the train data
  X_train_reduced_transformed = vect.transform(X_train_reduced['text'])
  X_test_transformed = vect.transform(X_test['text'])

  # Add the extra features
  X_train_with_features = X_train_reduced[['length_of_doc','digit_count','non_word_char_count']].to_numpy()
  X_test_with_features = X_test[['length_of_doc','digit_count','non_word_char_count']].to_numpy()

  X_train_with_features = hstack([X_train_reduced_transformed, X_train_with_features])
  X_test_with_features = hstack([X_test_transformed, X_test_with_features])

  # Fitting the model to the transformed data and computing score
  model = LogisticRegression(C=100, max_iter=1000).fit(X_train_with_features, y_train_reduced)
  y_pred = model.predict_proba(X_test_with_features)[:,1]
  auc_score = roc_auc_score(y_test, y_pred)

  # Sorted index
  sorted_idx = model.coef_[0].argsort()
  smallest_coefs = sorted_idx[:10]
  largest_coefs = sorted_idx[-10:][::-1]

  # Getting the feature values with largest and smallest coefs
  feature_names = np.array(list(vect.get_feature_names_out()) + ['length_of_doc','digit_count','non_word_char_count'])
  smallest_coefs = list(feature_names[smallest_coefs])
  largest_coefs = list(feature_names[largest_coefs])

  return (auc_score, smallest_coefs, largest_coefs)
answer_eleven()

(np.float64(0.9931964416073884),
 [np.str_('. '),
  np.str_('..'),
  np.str_(' i'),
  np.str_('at'),
  np.str_(' m'),
  np.str_('n '),
  np.str_('he'),
  np.str_('i '),
  np.str_('ok'),
  np.str_('? ')],
 [np.str_('digit_count'),
  np.str_('co'),
  np.str_('ne'),
  np.str_('xt'),
  np.str_(' st'),
  np.str_('xt '),
  np.str_('s '),
  np.str_('es'),
  np.str_(' f'),
  np.str_('on')])